apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: AuthorService
  name: Author-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: Author.example.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: AuthorService
            port:
              number: 8001